import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navebar from "@/components/Navebar";
import UserSync from "@/components/user-sync";
import { Toaster } from "sonner";
import { getCart } from "@/components/lip/actions/cart";

const notoSans = Noto_Sans({ variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cart = await getCart();
  return (
    <ClerkProvider>
      <html lang="en" className={notoSans.variable}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navebar cart={cart} />
          <UserSync />
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
